# Generated by Django 5.1.7 on 2025-05-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
