# Generated by Django 5.1.7 on 2025-05-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todoapp_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
