# Generated by Django 5.1.7 on 2025-05-27 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todoapp_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
