# Generated by Django 5.1.7 on 2025-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todoapp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
